steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/event-management-system-430621/event-management-system2:$COMMIT_SHA', '.']
  id: 'Build Docker image'

- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/event-management-system-430621/event-management-system2:$COMMIT_SHA']
  id: 'Push Docker image'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: gcloud
  args: ['run', 'deploy', 'event-management-system2',
         '--image', 'gcr.io/event-management-system-430621/event-management-system2:$COMMIT_SHA',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--allow-unauthenticated',
         '--set-env-vars', "ASPNETCORE_ENVIRONMENT=Development,ConnectionStrings__DefaultConnection=Server=34.44.194.190;Database=EventManagementFinalNewNew;User Id=sqlserver;Password=event@123",
         '--port', '8080']
  id: 'Deploy to Cloud Run'
  
images:
- 'gcr.io/event-management-system-430621/event-management-system2:$COMMIT_SHA'

timeout: 1200s
