name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies for EventManagementProject
        run: dotnet restore EventManagementProject/EventManagementProject.csproj

      - name: Restore dependencies for EventManagementTest
        run: dotnet restore EventManagementTest/EventManagementTest.csproj

      - name: Build EventManagementProject
        run: dotnet build EventManagementProject/EventManagementProject.csproj --no-restore

      - name: Build EventManagementTest
        run: dotnet build EventManagementTest/EventManagementTest.csproj --no-restore

      - name: Run tests
        run: dotnet test EventManagementTest/EventManagementTest.csproj --no-build --verbosity normal
