name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: [Python CI with pytest]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore EventManagement/EventManagement.csproj

      - name: Build the main application
        run: dotnet build EventManagement/EventManagement.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test EventManagement.Tests/EventManagement.Tests.csproj --no-restore --verbosity normal

  build-docker-image:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in directory
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -f Dockerfile -t aaryamaster/eventsystem .

      - name: Push Docker image to Docker Hub
        run: docker push aaryamaster/eventsystem

  notify-on-failure:
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Notify on failure
        run: echo 'The triggering workflow failed'
